version: '3.6'

services:

  server:
    image: node:16-alpine
    volumes:
      - .:/CIMonitor
    working_dir: /CIMonitor
    user: ${USERID}:${GROUPID}
    command: sh -c "npm run server"
    ports:
      - "3030:3030"

  dashboard:
    image: node:16-alpine
    volumes:
      - .:/CIMonitor
    working_dir: /CIMonitor
    user: ${USERID}:${GROUPID}
    command: sh -c "npm run dashboard"
    ports:
      - "3031:3031"

networks:

  default:
    name: cimonitor
