version: '3.6'

services:

  server:
    build:
      context: docker/server
      target: server
    volumes:
      - .:/CIMonitor
    user: ${USERID}:${GROUPID}
    command: sh -c "npm run server"
    ports:
      - "3030:3030"

  module-client:
    build:
      context: docker/module-client
      target: module-client
    volumes:
      - .:/CIMonitor
    user: ${USERID}:${GROUPID}
    command: sh -c "npm run module-client"

  dashboard:
    build:
      context: docker/server
      target: dashboard
    volumes:
      - .:/CIMonitor
    user: ${USERID}:${GROUPID}
    command: sh -c "npm run dashboard"
    ports:
      - "3031:3031"

networks:

  default:
    name: cimonitor
