site_name: CIMonitor
theme: readthedocs
repo_url: https://github.com/FuturePortal/CIMonitor
site_author: Rick van der Staaij
dev_addr: 0.0.0.0:9998
extra_css:
  - style.css
pages:
  - Home: index.md
  - Getting started: getting-started.md
  - Running CIMonitor:
    - Docker: run/docker.md
    - Kubernetes: run/kubernetes.md
    - Locally with node: run/locally.md
    - Raspberry Pi (ARM): run/raspberry-arm.md
  - Configuration:
    - Evironment variables: config/environment.md
    - Firebase: config/firebase.md
  - Webhooks:
    - GitHub: webhook/github.md
    - GitLab: webhook/gitlab.md
    - Read the docs: webhook/readthedocs.md
  - Modules: modules.md
  - Module:
    - GPIO: module/gpio.md
  - Module client: module-client.md
