name: Build the CIMonitor latest container
on:
  push:
    branches:
      - master
jobs:
  test:
    uses: ./.github/workflows/job--test-and-lint.yml

  build:
    uses: ./.github/workflows/job--build-and-tag.yml
    needs: test
    with:
      TAG: latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
