name: Tag new CIMonitor release
on:
  push:
    tags:
      - '*'
jobs:
  test:
    name: Test
    uses: ./.github/workflows/job--test-and-lint.yml

  server:
    name: Server
    uses: ./.github/workflows/job--build-and-tag.yml
    needs: test
    with:
      BASE_IMAGE: node:16-slim
      DOCKER_DIRECTORY: docker/server
      DOCKER_IMAGE: cimonitor/server:${GITHUB_REF/refs\/tags\//}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  server-arm:
    name: Server ARM
    uses: ./.github/workflows/job--build-and-tag.yml
    needs: test
    with:
      BASE_IMAGE: arm32v7/node:16-slim
      DOCKER_DIRECTORY: docker/server
      DOCKER_IMAGE: cimonitor/server:${GITHUB_REF/refs\/tags\//}-arm
      QEMU_ARCH: arm
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  module-client:
    name: Module client
    uses: ./.github/workflows/job--build-and-tag.yml
    needs: test
    with:
      BASE_IMAGE: node:16-slim
      DOCKER_DIRECTORY: docker/module-client
      DOCKER_IMAGE: cimonitor/module-client:${GITHUB_REF/refs\/tags\//}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  module-client-arm:
    name: Module client ARM
    uses: ./.github/workflows/job--build-and-tag.yml
    needs: test
    with:
      BASE_IMAGE: arm32v7/node:16-slim
      DOCKER_DIRECTORY: docker/module-client
      DOCKER_IMAGE: cimonitor/module-client:${GITHUB_REF/refs\/tags\//}-arm
      QEMU_ARCH: arm
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
