name: Tag new CIMonitor release
on:
  push:
    tags:
      - '*'
jobs:
  test:
    uses: ./.github/workflows/job--test-and-lint.yml

  build:
    uses: ./.github/workflows/job--build-and-tag.yml
    needs: test
    with:
      TAG: ${GITHUB_REF/refs\/tags\//}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
