name: Tag new CIMonitor release
on:
  push:
    tags:
      - '*'
jobs:
  test:
    name: Test
    uses: ./.github/workflows/job--test-and-lint.yml

  build:
    name: Build
    uses: ./.github/workflows/job--build-containers.yml
    needs: test
    with:
      BASE_TAG: ${GITHUB_REF/refs\/tags\//}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
